// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvAQrUW9jmSd0Chy1qdW9kpKRgxtnbCmg',
    appId: '1:206779842773:web:ed4011f2a3ee2b16c8625c',
    messagingSenderId: '206779842773',
    projectId: 'registration-4c21b',
    authDomain: 'registration-4c21b.firebaseapp.com',
    storageBucket: 'registration-4c21b.firebasestorage.app',
    measurementId: 'G-YHH7QZMRDK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8grM9_-r8hXe5K_QhMCR9NwmIZgh3yT8',
    appId: '1:206779842773:android:27cdbfd460fac438c8625c',
    messagingSenderId: '206779842773',
    projectId: 'registration-4c21b',
    storageBucket: 'registration-4c21b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMzBGmJLKUzO1zt5jjw4sY4pu29M9IB3k',
    appId: '1:206779842773:ios:c9f250c1fa612518c8625c',
    messagingSenderId: '206779842773',
    projectId: 'registration-4c21b',
    storageBucket: 'registration-4c21b.firebasestorage.app',
    iosBundleId: 'com.example.registrationAppFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMzBGmJLKUzO1zt5jjw4sY4pu29M9IB3k',
    appId: '1:206779842773:ios:c9f250c1fa612518c8625c',
    messagingSenderId: '206779842773',
    projectId: 'registration-4c21b',
    storageBucket: 'registration-4c21b.firebasestorage.app',
    iosBundleId: 'com.example.registrationAppFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBvAQrUW9jmSd0Chy1qdW9kpKRgxtnbCmg',
    appId: '1:206779842773:web:e923c686c39403a0c8625c',
    messagingSenderId: '206779842773',
    projectId: 'registration-4c21b',
    authDomain: 'registration-4c21b.firebaseapp.com',
    storageBucket: 'registration-4c21b.firebasestorage.app',
    measurementId: 'G-DXD44PPWKR',
  );
}
